server:
  port: 9528

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hyl_product?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  application:
    name: study-provider
  zipkin:
         base-url: http://localhost:9411/ # zipkin的地址
         discovery-client-enabled: false  #让注册中心把它当成url  而不要当成服务
  sleuth:
     sampler:
       probability: 1.0 #标识全部采集{0-1}
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alibaba:
      seata:
          tx-service-group: study-provider
# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.hyl.study.api.entity
  configuration:
    map-underscore-to-camel-case: true
    # 配置slq打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    logic-delete-value: 1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector